/**
 * Server State & Datastore
 * Authoritative in-memory and persistence-backed storage for users,
 * audit logs, programs, chapters, and scoring events.
 */

import type {
  UserProfile,
  AuditLogEntry,
  StudyProgram,
  Chapter,
  ScoreEvent,
} from '../src/types';
import { InMemoryScoringStore } from '../src/lib/scoring/scoringStore';
import { INITIAL_LEADERBOARD_SEED } from './routes/scoring';

export const serverScoringStore = new InMemoryScoringStore();

// Initialize scoring store with leaderboard seed
for (const entry of INITIAL_LEADERBOARD_SEED) {
  serverScoringStore.leaderboard.set(entry.uid, { ...entry });
}

// Master authoritative user collection on server
export const serverUsersMap = new Map<string, UserProfile>();

const INITIAL_USERS: UserProfile[] = [
  {
    uid: 'uid_admin_01',
    username: 'admin',
    displayName: 'StudyRank Administrator',
    role: 'admin',
    accountStatus: 'approved',
    createdAt: '2026-08-01T08:00:00.000Z',
    lastActiveAt: new Date().toISOString(),
    totalPoints: 1250,
    studyPoints: 750,
    habitPoints: 500,
    streak: 12,
    rank: 1,
    email: 'admin@studyrank.internal',
  },
  {
    uid: 'uid_alex_02',
    username: 'alex_rivera',
    displayName: 'Alex Rivera',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-05T09:30:00.000Z',
    lastActiveAt: new Date(Date.now() - 15 * 60000).toISOString(),
    totalPoints: 1420,
    studyPoints: 920,
    habitPoints: 500,
    streak: 14,
    rank: 2,
    email: 'alex_rivera@studyrank.internal',
  },
  {
    uid: 'u_sarah_01',
    username: 'sarah_chen',
    displayName: 'Sarah Chen',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-02T10:00:00.000Z',
    lastActiveAt: new Date(Date.now() - 30 * 60000).toISOString(),
    totalPoints: 1640,
    studyPoints: 1020,
    habitPoints: 620,
    streak: 18,
    rank: 1,
    email: 'sarah_chen@studyrank.internal',
  },
  {
    uid: 'u_marcus_03',
    username: 'marcus_vance',
    displayName: 'Marcus Vance',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-10T11:00:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    totalPoints: 1180,
    studyPoints: 780,
    habitPoints: 400,
    streak: 9,
    rank: 3,
    email: 'marcus_vance@studyrank.internal',
  },
  {
    uid: 'u_priya_04',
    username: 'priya_sharma',
    displayName: 'Priya Sharma',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-12T14:15:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    totalPoints: 980,
    studyPoints: 640,
    habitPoints: 340,
    streak: 7,
    rank: 4,
    email: 'priya_sharma@studyrank.internal',
  },
  {
    uid: 'u_david_05',
    username: 'david_kim',
    displayName: 'David Kim',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-15T16:20:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    totalPoints: 850,
    studyPoints: 550,
    habitPoints: 300,
    streak: 5,
    rank: 5,
    email: 'david_kim@studyrank.internal',
  },
  {
    uid: 'u_jordan_06',
    username: 'jordan_blake',
    displayName: 'Jordan Blake',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-16T17:00:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    totalPoints: 760,
    studyPoints: 510,
    habitPoints: 250,
    streak: 6,
    rank: 6,
    email: 'jordan_blake@studyrank.internal',
  },
  {
    uid: 'u_elena_07',
    username: 'elena_rostova',
    displayName: 'Elena Rostova',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-18T18:00:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    totalPoints: 690,
    studyPoints: 450,
    habitPoints: 240,
    streak: 4,
    rank: 7,
    email: 'elena_rostova@studyrank.internal',
  },
  {
    uid: 'u_liam_08',
    username: 'liam_oconnor',
    displayName: 'Liam O\'Connor',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-20T19:00:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    totalPoints: 620,
    studyPoints: 400,
    habitPoints: 220,
    streak: 3,
    rank: 8,
    email: 'liam_oconnor@studyrank.internal',
  },
  {
    uid: 'u_maya_09',
    username: 'maya_patel',
    displayName: 'Maya Patel',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-22T20:00:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    totalPoints: 550,
    studyPoints: 360,
    habitPoints: 190,
    streak: 4,
    rank: 9,
    email: 'maya_patel@studyrank.internal',
  },
  {
    uid: 'u_lucas_10',
    username: 'lucas_silva',
    displayName: 'Lucas Silva',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-24T21:00:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    totalPoints: 480,
    studyPoints: 310,
    habitPoints: 170,
    streak: 2,
    rank: 10,
    email: 'lucas_silva@studyrank.internal',
  },
  {
    uid: 'u_chloe_11',
    username: 'chloe_bennett',
    displayName: 'Chloe Bennett',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-26T22:00:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 42).toISOString(),
    totalPoints: 420,
    studyPoints: 280,
    habitPoints: 140,
    streak: 2,
    rank: 11,
    email: 'chloe_bennett@studyrank.internal',
  },
  {
    uid: 'u_noah_12',
    username: 'noah_williams',
    displayName: 'Noah Williams',
    role: 'user',
    accountStatus: 'approved',
    createdAt: '2026-08-28T23:00:00.000Z',
    lastActiveAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    totalPoints: 360,
    studyPoints: 240,
    habitPoints: 120,
    streak: 1,
    rank: 12,
    email: 'noah_williams@studyrank.internal',
  },
  // Pending registrations
  {
    uid: 'u_pending_01',
    username: 'james_miller',
    displayName: 'James Miller',
    role: 'user',
    accountStatus: 'pending',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastActiveAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    totalPoints: 0,
    studyPoints: 0,
    habitPoints: 0,
    streak: 0,
    rank: 0,
    email: 'james_miller@studyrank.internal',
  },
  {
    uid: 'u_pending_02',
    username: 'ananya_patel',
    displayName: 'Ananya Patel',
    role: 'user',
    accountStatus: 'pending',
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    lastActiveAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    totalPoints: 0,
    studyPoints: 0,
    habitPoints: 0,
    streak: 0,
    rank: 0,
    email: 'ananya_patel@studyrank.internal',
  },
  {
    uid: 'u_pending_03',
    username: 'li_wei',
    displayName: 'Li Wei',
    role: 'user',
    accountStatus: 'pending',
    createdAt: new Date(Date.now() - 3600000 * 26).toISOString(),
    lastActiveAt: new Date(Date.now() - 3600000 * 26).toISOString(),
    totalPoints: 0,
    studyPoints: 0,
    habitPoints: 0,
    streak: 0,
    rank: 0,
    email: 'li_wei@studyrank.internal',
  },
  // Banned accounts
  {
    uid: 'uid_banned_03',
    username: 'banned_student',
    displayName: 'Disqualified Account',
    role: 'user',
    accountStatus: 'banned',
    createdAt: '2026-08-18T10:00:00.000Z',
    lastActiveAt: '2026-08-20T12:00:00.000Z',
    totalPoints: 0,
    studyPoints: 0,
    habitPoints: 0,
    streak: 0,
    rank: 0,
    email: 'banned_student@studyrank.internal',
  },
  {
    uid: 'u_banned_02',
    username: 'cheater_bot_99',
    displayName: 'Flagged Automation Script',
    role: 'user',
    accountStatus: 'banned',
    createdAt: '2026-08-21T04:00:00.000Z',
    lastActiveAt: '2026-08-21T04:15:00.000Z',
    totalPoints: 0,
    studyPoints: 0,
    habitPoints: 0,
    streak: 0,
    rank: 0,
    email: 'cheater_bot_99@studyrank.internal',
  },
  // Deactivated accounts
  {
    uid: 'u_deactivated_01',
    username: 'sam_taylor',
    displayName: 'Sam Taylor',
    role: 'user',
    accountStatus: 'deactivated',
    createdAt: '2026-08-01T12:00:00.000Z',
    lastActiveAt: '2026-08-25T14:00:00.000Z',
    totalPoints: 340,
    studyPoints: 200,
    habitPoints: 140,
    streak: 0,
    rank: 0,
    email: 'sam_taylor@studyrank.internal',
  },
];

for (const u of INITIAL_USERS) {
  serverUsersMap.set(u.uid, { ...u });
  serverScoringStore.users.set(u.uid, { ...u });
}

// Authoritative audit log entries. NEVER stores PINs!
export const serverAuditLogs: AuditLogEntry[] = [
  {
    id: 'audit_01',
    actorUid: 'uid_admin_01',
    actorUsername: 'admin',
    action: 'USER_APPROVED',
    targetUid: 'u_sarah_01',
    targetUsername: 'sarah_chen',
    timestamp: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    metadata: { note: 'Initial onboarding approved' },
  },
  {
    id: 'audit_02',
    actorUid: 'uid_admin_01',
    actorUsername: 'admin',
    action: 'USER_BANNED',
    targetUid: 'uid_banned_03',
    targetUsername: 'banned_student',
    timestamp: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    metadata: { reason: 'Academic integrity and automated scraping violation' },
  },
  {
    id: 'audit_03',
    actorUid: 'uid_admin_01',
    actorUsername: 'admin',
    action: 'ACCOUNT_DEACTIVATED',
    targetUid: 'u_deactivated_01',
    targetUsername: 'sam_taylor',
    timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
    metadata: { reason: 'Student semester break request' },
  },
  {
    id: 'audit_04',
    actorUid: 'uid_admin_01',
    actorUsername: 'admin',
    action: 'USER_APPROVED',
    targetUid: 'u_marcus_03',
    targetUsername: 'marcus_vance',
    timestamp: new Date(Date.now() - 3600000 * 18).toISOString(),
    metadata: { note: 'Registration verified' },
  },
  {
    id: 'audit_05',
    actorUid: 'uid_admin_01',
    actorUsername: 'admin',
    action: 'PROGRAM_INSPECTED',
    targetUid: 'uid_alex_02',
    targetUsername: 'alex_rivera',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    metadata: { programName: 'Full-Stack Distributed Systems Masterclass' },
  },
];

// Sample programs for inspection
export const serverSamplePrograms: Record<string, StudyProgram[]> = {
  uid_alex_02: [
    {
      id: 'prog_alex_01',
      ownerUid: 'uid_alex_02',
      name: 'Full-Stack Distributed Systems Masterclass',
      description: 'Comprehensive curriculum covering distributed consensus, Raft, and cloud architectures.',
      startDate: '2026-08-01',
      targetDate: '2026-10-15',
      status: 'active',
      totalSubjects: 4,
      totalChapters: 24,
      completedChapters: 18,
      progressPercentage: 75,
      createdAt: '2026-08-01T08:00:00.000Z',
      updatedAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ],
  u_sarah_01: [
    {
      id: 'prog_sarah_01',
      ownerUid: 'u_sarah_01',
      name: 'Advanced Algorithms & Data Structures',
      description: 'Competitive programming algorithms, graph theory, and dynamic programming.',
      startDate: '2026-07-15',
      targetDate: '2026-09-30',
      status: 'active',
      totalSubjects: 5,
      totalChapters: 30,
      completedChapters: 28,
      progressPercentage: 93,
      createdAt: '2026-07-15T08:00:00.000Z',
      updatedAt: new Date(Date.now() - 7200000).toISOString(),
    },
  ],
};
